[tox]
minversion = 4.0
envlist =
    lint
    pkg
    py{37,38,39,310,311,312,313}-cocotb{19,20}-{pytest,make}
    py{37,38,39,310,311,312}-cocotb18-{pytest,make}
    py{37,38,39,310,311}-cocotb17-{pytest,make}
    py{37,38,39,310}-cocotb16-{pytest,make}
skip_missing_interpreters=true

# Use tox-uv for faster environment creation and package installation
requires =
    tox-uv

[testenv]
description = Run {envname}
allowlist_externals=
    make
    bash
setenv =
   make: PYTHONPATH = {toxinidir}:{toxinidir}/tests/pytests
   make: COCOTB_REDUCED_LOG_FMT=1
passenv =
  make: VERILOG_SIM
  make: LM_LICENSE_FILE
  make: PYTHONPATH
  make: VHDL_SIM
deps =
    cocotb16: cocotb==1.6
    cocotb17: cocotb==1.7
    cocotb18: cocotb==1.8
    cocotb19: cocotb==1.9
    cocotb20: cocotb==2.0
    pytest
commands =
    pytest: pytest
    make: make tests

[testenv:lint]
description = Run pre-commit lints
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[testenv:pkg]
description = build and check package distribution
skip_install = true
deps =
    build
    twine
commands =
    python -m build
    twine check --strict dist/*

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[gh-actions:env]
COCOTB_VERSION =
    1.6: cocotb16
    1.7: cocotb17
    1.8: cocotb18
    1.9: cocotb19
    2.0: cocotb20
